# Generated by Django 4.0.5 on 2022-06-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('groups', '0001_initial'),
        ('animals', '0002_animal_characteristics_animal_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(to='characteristics.characteristic'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
